[package]
authors = ["Yao <yaojianpin@sohu.com>"]
description = "a fast, tiny, extensiable workflow engine"
edition = "2021"
keywords = ["workflow"]
license = "MIT"
name = "acts"
repository = "https://github.com/yaojianpin/acts.git"
version = "0.8.1"

[dependencies]
acts-tag = { version = "0.2.0" }
async-trait = "0.1.57"
chrono = "0.4.22"
colored = "2.0.0"
criterion = "0.4.0"
futures = "0.3.25"
lru = "0.8.1"
nanoid = "0.4.0"
once_cell = "1.15.0"
regex = "1.6.0"
rhai = { version = "1.13.0", features = ["internals", "sync"] }
rocksdb = { version = "0.20.0", features = ["lz4", "multi-threaded-cf"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.94"
serde_yaml = "0.9.25"
thiserror = "1.0.34"
tokio = { version = "1.21.0", features = ["full"] }
tracing = "0.1.37"

[dev-dependencies]
criterion = { version = "0.4.0", features = ["async_tokio"] }

[features]
default = []
local_store = []

[[bench]]
harness = false
name = "workflow"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
