
[package]
authors = ["Yao <yaojianpin@sohu.com>"]
description = "a fast, tiny, extensiable workflow engine"
edition = "2021"
keywords = ["workflow"]
license = "Apache-2.0"
name = "acts"
repository = "https://github.com/yaojianpin/acts.git"
version = "0.9.1"

[dependencies]
async-trait = "0.1.57"
chrono = "0.4.22"
duckdb = { version = "0.10.0", features = ["bundled", "r2d2"], optional = true }
futures = "0.3.25"
hex = { version = "0.4.3", features = ["serde"] }
lru = "0.8.1"
nanoid = "0.4.0"
once_cell = "1.15.0"
r2d2 = { version = "0.8.10", optional = true }
regex = "1.6.0"
rhai = { version = "1.13.0", features = ["internals", "sync"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.94"
serde_yaml = "0.9.25"
thiserror = "1.0.34"
tokio = { version = "1.21.0", features = ["full"] }
tracing = "0.1.37"
wasmtime = { version = "18.0.2", optional = true }
wasmtime-wasi = { version = "18.0.3", optional = true }
wit-bindgen = { version = "0.21.0", optional = true }
wit-component = { version = "0.201.0", optional = true }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["async_tokio"] }

[features]
default = []
store = ["duckdb", "r2d2"]
wit = ["wit-bindgen", "wit-component", "wasmtime-wasi", "wasmtime"]

[[bench]]
harness = false
name = "workflow"

[profile.dev]
debug = 1

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true

workspace = { members = ["examples/packet/pack1"] }
