name: test1
ver: 1.0
env:
  a: "true"
  b: ${ 7 + 3 + 11 }
  c: 5.5
  d: [2, 4, 5.5, "a"]
  e: aaaa
jobs:
  - id: job2
    steps:
      - name: job2 step 1
        run: print(env.get("e"))
      - name: job2 step 2
        run: print("job2 step 2")
  - id: job1
    steps:
      - name: step 1
        if: true
        run: |
          print("step 1")
      - name: step 2
        on:
        run: |
          print("step 2");
          print(env.get("aaaaaaaaa"));

          env.set("b", 100);
          print(env.get("b"));
          let v = 50;
          console::log(`v=${v}`);
          console::dbg(`v=${v}`);
          console::info(`v=${v}`);
          console::wran(`v=${v}`);
          console::error(`v=${v}`);
          //let a = env.get("cccc");
          //act::abc(a);
          //act::log("aaaaa");

      - name: step 3
        env:
          e: abc
        branches:
          - name: branch 1
            if: env.get("a") == "true"
            to: job.a1
            steps:
              - name: branch 1.1
                run: |
                  //sleep(3.0);
                  print("branch 1.1");
                  print(env.get("b"));
              - name: branch 1.2
                run: print("branch 1.2")
          - name: branch 2
            if: env.get("a") == "false"
            steps:
              - name: branch 2.1
                run: print("branch 2.1")
        run: |
          print("step 3");
          print(env.get("e"));
          print(env.get("b"));
          // print(a);
          //throw "hello";

      - name: step 4
        run: print(`step 4`);
