name: event_test
id: m1
outputs:
  value: 0
jobs:
  - name: job1
    steps:
      - name: step 1
        id: step1
        on:
          init: |
            print("init");
            env.set("value", 10);
          complete: |
            print("complete");
          error: |
            print("error");
          a: |
            print("custom message");
        run: |
          print("step 1");
      - name: step 2
      - name: step 3
      - name: step 4